package com.shwangce.nt10g.client.util;

/**
 * Created by Administrator on 2016/9/14 0014.
 */
public enum WorkEventType {
    COMMUNICATE_EVENT_FINDNEWDEVICE,
    COMMUNICATE_EVENT_DISCOVERYFINISHED,
    COMMUNICATE_EVENT_CONNECTSUCCESS,
    COMMUNICATE_EVENT_ERROR,
    COMMUNICATE_EVENT_CONNECTLOSS,
    COMMUNICATE_EVENT_DATAARRAIVE,

    ETHERNET_EVENT_LINKSTATE,

    SETACCESS_EVENT_SUCCESS,
    SETACCESS_EVENT_FAIL,

    TEST_EVENT_FAIL,
    TEST_EVENT_INFO,

    SPEEDTEST_EVENT_GETCLIENT,
    SPEEDTEST_EVENT_GETSERVER,
    SPEEDTEST_EVENT_DOWNLOADING,
    SPEEDTEST_EVENT_DOWNLOADED,
    SPEEDTEST_EVENT_UPLOADING,
    SPEEDTEST_EVENT_UPLOADED,
    SPEEDTEST_EVENT_COMPLETE,
    SPEEDTEST_EVENT_HXBOXRESULT,
    SPEEDTEST_EVENT_GETUSERINFO_GD10000,

    TRADEOFFTEST_EVENT_UPLOADING,
    TRADEOFFTEST_EVENT_DOWNLOADING,
    TRADEOFFTEST_EVENT_COMPLETE,
    TRADEOFFTEST_EVENT_FAIL
}
